### ISSUE TITLE
Server-Sent Events giving `TypeError: undefined is not an object (evaluating 'c.signal.aborted')`

### ISSUE THREAD

**Issue by Joxtacy** [bunsvr/app#1]
I tried out Server-Sent Events in Stric, but I keep running into an issue when I call my endpoint.

Here is the stacktrace:
```
1 | function anonymous(pull,abort,cancel,o
2 | ) {
3 | return c=>new Response(new ReadableStream({type:'direct',pull:_=>{while(!c.signal.aborted)pull(_,c);abort(_,c)},cancel:_=>{cancel(_,c)}}),o)
                                                                                                                                           ^
TypeError: undefined is not an object (evaluating 'c.signal.aborted')
      at pull (:3:136)
      at readDirectStream (:1:21)
GET - /sse failed
```

Here is my `main.routes.ts`:

```ts
import { routes } from '@stricjs/app';
import { events } from '@stricjs/app/stream';

export default routes()
  .get('/sse', (ctx) => {
    let interval: Timer | undefined;
    const evs = events((controller, ctx) => {
      interval = setInterval(() => {
        controller.write('hello');
      }, 1000);
    });
    evs.abort((controller, ctx) => {
      console.log('abort');
      clearInterval(interval);
    });
    evs.cancel((controller, ctx) => {
      console.log('cancel');
      clearInterval(interval);
    });

    return evs.send()(ctx);
  })

```

Not sure what `signal.aborted` is supposed to be on the, what I assume is, the context that is being passed in to the function returned from `evs.send()`.

Let me know if I can help out in any way or if you have any other questions.

Thank you!

**Comment by aquapi** [comment]
I see why
`@stricjs/utils` is not up to date with `@stricjs/app` changes @Joxtacy

**Comment by Joxtacy** [comment]
I understand. Thanks for the response! I was looking around in the code to try and figure out what could be done to fix it, but honestly I'm not sure that I fully understand what is going on.

**Comment by aquapi** [comment]
@Joxtacy I actually scrapped this project a while ago
I'm trying to make a much simpler framework with better performance 
For rn I recommend Hono
You can follow the framework development here: https://github.com/bit-js/byte

**Comment by Joxtacy** [comment]
@aquapi I see. I'll take a look at other options for now then. I'll also check out your new project. Looking forward to seeing more. :)
