### ISSUE TITLE
An error occurs if add a variable to the `fallback` function when there is no GET route

### ISSUE THREAD

**Issue by namchivas2k** [bunsvr/app#2]
This code in file `index.ts`

```typescript
import { init } from '@stricjs/app';

init({
    routes: ['./src'],
    fallback: function (ctx) {
        return new Response('404 - NotFound', { status: 404 })
    }
});
```

and this code in file `src/index.routes.ts`
```typescript
import { routes } from "@stricjs/app";

export default routes()
    .post('/hello', () => new Response('Hello POST'))
 
```

and this is error log
![Screenshot from 2024-02-16 18-14-44](https://github.com/bunsvr/app/assets/80379064/c551e657-9089-4d49-9813-c9f07336a5e8)

**Comment by aquapi** [comment]
@namchivas2k Sorry but I scrapped this project
I suggest you use other frameworks like Hono or Elysia
I'm gonna make a new one but not really a framework but if you are interested take a look at
https://github.com/bit-js

**Comment by JohnRoseDev** [comment]
@aquapi can you confirm that the whole stric framework (https://stricjs.netlify.app/) is scrapped or are you referring to a specific repo? thanks

**Comment by aquapi** [comment]
@JohnRoseDev yep you're right the whole thing is scrapped
