### ISSUE TITLE
Cannot find module '@stricjs/app/send' or its corresponding type declarations.ts(2307)

### ISSUE THREAD

**Issue by Succubussix** [bunsvr/app#4]
this is fine no error lint. but not working, It will throw  ```error: Cannot find module "@stricjs/app/lib/send" from xxx``` at console
```ts
import { text } from '@stricjs/app/lib/send';
```

this is fine **but** it has error. and its **working** xD wont throw error at console. but gonna throw at lint error swigly redline. 
```Cannot find module '@stricjs/app/send' or its corresponding type declarations.ts(2307)```
```ts
import { text } from '@stricjs/app/send';
```

please fix typescript types xD me no like errors even tho it works still in editor its red line xD because i think u move the .d.ts on library lib instead of root.

![image](https://github.com/bunsvr/app/assets/12135498/e586dc36-5cd8-4a11-b838-434857591aad)

**Comment by NerfedJabolo** [comment]
Hi, this project has been scrapped. Sorry for the inconvenience caused.

**Comment by Succubussix** [comment]
> Hi, this project has been scrapped. Sorry for the inconvenience caused.

aw :( why is it scrapped.

**Comment by NerfedJabolo** [comment]
https://github.com/bunsvr/app/issues/3#issuecomment-1965582054

**Comment by gurachan** [comment]
thats unfortunate .. last night I did a bit searching about other lib that does the same I found one elysiajs, I guess ima give that i try today.
